language: minimal

services:
  - docker

stages:
  - build
  - success

before_install:
  - docker login --username ${CI_REGISTRY_USERNAME} -p ${CI_REGISTRY_TOKEN} ${CI_REGISTRY_URL}

jobs:
  include:
    - stage: build
      name: "Build Docker Image and push to registry"
      script:
        - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}/cart:${TRAVIS_COMMIT}
                  -f docker/cart/Dockerfile . --no-cache"
        - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/cart:${TRAVIS_COMMIT}"
    - stage: success
      name: "Report success"
      script:
        - echo "SUCCESS"

