#docker compose file
version: '3.1'

networks:
  redis-net:
  web:

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - redis-net

  cart-service:
    image: registry.github.com/kamilkoduo/digicart/cart:local
    command: "/app/cart/build"
    ports:
      - 80:8080
    environment:
      - REDIS_ADDRESS=redis:6379
      - APP_ADDRESS=0.0.0.0:8080
      - GIN_MODE=debug
    restart: always
    networks:
      - redis-net
      - web